Final/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^warehouse/', include('warehouse.urls', namespace='warehouse')),

    # ==================== TESTING PURPOSES ==================== #
    url(r'^testing/$', views.testing, name='testing'),
    url(r'^add_tubs/$', views.add_tubs, name='add_tubs'),
    url(r'^del_tubs/$', views.del_tubs, name='del_tubs'),
    url(r'^add_bottles/$', views.add_bottles, name='add_bottles'),
    url(r'^del_bottles/$', views.del_bottles, name='del_bottles'),
    url(r'^add_customers/$', views.add_customers, name='add_customers'),
    url(r'^del_customers/$', views.del_customers, name='del_customers'),
    url(r'^add_orders/$', views.add_orders, name='add_orders'),
    url(r'^del_orders/$', views.del_orders, name='del_orders'),
]

sales/urls.py
from django.conf.urls import url
from . import views

app_name="sales"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    # url(r'^add_order_customer', views.add_order_customer, name='add_order_customer'),
    # url(r'^add_order/(?P<customer_id>[0-9]+)/$', views.OrderAdd.as_view(), name='add_order'),
    # url(r'^pre_order_update/$', views.pre_order_update, name='pre_order_update'),
    # url(r'^order_update/(?P<order_number>[0-9]+)$', views.order_update, name='order_update'),
    url(r'^customers/$', views.Customers.as_view(), name='customers'),
    url(r'^customers/(?P<pk>[0-9]+)/$', views.CustomerProfile.as_view(), name='customer_details'),
    url(r'^customers/new/$', views.NewCustomer.as_view(), name='new_customer'),
    url(r'^customer/update/(?P<pk>[0-9]+)/$', views.EditCustomer.as_view(), name='edit_customer'),
    url(r'^orders/pre_add_order$', views.pre_add_order, name='pre_add_order'),
    url(r'^orders/new/(?P<pk>[0-9]+)/$', views.NewOrder.as_view(), name='new_order'),
    url(r'^orders/new/(?P<pk>[0-9]+)/new_queued_tub/$', views.NewQueuedTub.as_view(), name='new_queued_tub'),
    url(r'^orders/new/(?P<pk>[0-9]+)/new_queued_bottle/$', views.NewQueuedBottle.as_view(), name='new_queued_bottle'),
    url(r'^orders/(?P<cust>[0-9]+)/(?P<pk>[0-9]+)/$', views.OrderDetail.as_view(), name='order_detail'),
    url(r'^orders/(?P<pk>[0-9]+)/(?P<cust>[0-9]+)/add_items', views.add_items, name='add_items'),
    url(r'^orders/(?P<pk>[0-9]+)/get_tubs', views.get_tubs, name='get_tubs'),
    url(r'^orders/(?P<pk>[0-9]+)/get_bottles', views.get_bottles, name='get_bottles'),

]

inventory/models.py
from django.db import models
from django.urls import reverse
from sales.models import *

# Create your models here.
class Tub(models.Model):
    TRUCK = 'TK'
    CUSTOMER = 'CS'
    DOCKED_EMPTY = 'DE'
    DOCKED_FULL = 'DF'
    STATUS_CHOICES = (
        (TRUCK, 'On Truck'),
        (CUSTOMER, 'Customer Site'),
        (DOCKED_FULL, 'Docked Full'),
        (DOCKED_EMPTY, 'Docked Empty'),
    )
    ICE_3 = 'ICE_3'
    ICE_16 = 'ICE_16'
    ICE_BLOCK = 'ICE_BLOCK'
    BAGGED_ICE_16 = 'BAGGED_ICE_16'
    BAGGED_ICE_3 = 'BAGGED_ICE_3'
    FILL_CHOICES = (
        (ICE_3, '3 Mill'),
        (ICE_16, '16 Mill'),
        (ICE_BLOCK, 'Ice Block'),
        (BAGGED_ICE_3, '3 Mill Bagged'),
        (BAGGED_ICE_16, '16 Mill Bagged'),
    )
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=DOCKED_EMPTY)
    fill = models.CharField(max_length=13, choices=FILL_CHOICES, default=ICE_3)
    barcode = models.CharField(max_length=15, unique=True)
    serial_number = models.CharField(max_length=15, unique=True, primary_key=True)
    emp_init = models.CharField(max_length=3)
    order = models.ForeignKey(Order, null=True, blank=False, on_delete=models.CASCADE)

    # This controls where the user gets taken when a new object is created
    @staticmethod
    def get_absolute_url():
        return reverse('warehouse:tubs')

    def __str__(self):
        return "{}-{}-{}, {} by {}".format(self.fill, self.barcode, self.serial_number, self.status, self.emp_init)


class Bottle(models.Model):
    TRUCK = 'TK'
    CUSTOMER = 'CS'
    DOCKED_EMPTY = 'DE'
    DOCKED_FULL = 'DF'
    RETEST = 'RT'
    STATUS_CHOICES = (
        (TRUCK, 'On Truck'),
        (CUSTOMER, 'Customer Site'),
        (DOCKED_FULL, 'Docked Full'),
        (DOCKED_EMPTY, 'Docked Empty'),
        (RETEST, 'Retest'),
    )
    ACETYLENE = 'AC'
    ARGON = 'AR'
    BEER_GAS = 'BG'
    CARBON_DIOXIDE = 'CD'
    GUINNESS_GAS = 'GS'
    HELIUM = 'HE'
    MIX_C2 = 'C2'
    MIX_C10 = 'C10'
    MIX_C25 = 'C25'
    NITROGEN = 'NI'
    OXYGEN = 'OX'
    STARGON = 'ST'
    SYPHON = 'SY'
    FILL_CHOICES = (
        (ACETYLENE, 'Acetylene'),
        (ARGON, 'Argon'),
        (BEER_GAS, 'Beer Gas'),
        (CARBON_DIOXIDE, 'Carbon Dioxide'),
        (GUINNESS_GAS, 'Guinness Gas'),
        (HELIUM, 'Helium'),
        (MIX_C2, 'Mix C2'),
        (MIX_C10, 'Mix C10'),
        (MIX_C25, 'Mix C25'),
        (NITROGEN, 'Nitrogen'),
        (OXYGEN, 'Oxygen'),
        (STARGON, 'Stargon'),
        (SYPHON, 'Syphon'),
    )
    SIZE_CHOICES = (
        ('T', 'T'),
        ('K', 'K'),
        ('S', 'S'),
        ('D', 'D'),
        ('Q', 'Q'),
        ('R', 'R'),
        ('50', '50'),
        ('40', '40'),
        ('20', '20'),
        ('15', '15'),
        ('10', '10'),
        ('5', '5'),
        ('2.5', '2.5'),
    )
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=DOCKED_FULL)
    fill = models.CharField(max_length=3, choices=FILL_CHOICES)
    size = models.CharField(max_length=3, choices=SIZE_CHOICES, default='T')
    barcode = models.CharField(max_length=15, unique=True)
    serial_number = models.CharField(max_length=15, unique=True, primary_key=True)
    emp_init = models.CharField(max_length=3)
    order = models.ForeignKey(Order, null=True, blank=False, on_delete=models.CASCADE)

    # This controls where the user gets taken when a new object is created
    @staticmethod
    def get_absolute_url():
        return reverse('warehouse:bottles')

    def __str__(self):
        return "{} {}-{}-{}-{} by {}".format(self.fill, self.size, self.status, self.barcode, self.serial_number, self.emp_init)

sales/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.


class Customer(models.Model):
    company = models.CharField(max_length=100, unique=True)
    contact_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=10, unique=True)
    customer_id = models.AutoField(primary_key=True)
    street_address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5)

    @staticmethod
    def get_absolute_url():
        return reverse('sales:customers')

    def __str__(self):
        return ' '.join([self.company, str(self.customer_id)])


class Order(models.Model):
    STATUS_CHOICES = (
        ('QUEUED', 'Queued'),
        ('SHIPPED', 'Shipped'),
    )
    order_number = models.AutoField(primary_key=True, unique=True)
    date_ordered = models.DateField()
    ship_date = models.DateField()
    emp_init = models.CharField(max_length=3)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    po_number = models.CharField(max_length=50, null=True, blank=True)
    branch = models.IntegerField(default=1)
    ship_method = models.CharField(max_length=50, null=True, blank=True)
    courier = models.CharField(max_length=50, null=True, blank=True)
    order_type = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True, choices=STATUS_CHOICES, default='QUEUED')

    def __str__(self):
        return "{} - {} - {} id: {}".format(self.customer, self.ship_date, self.order_number, self.order_number)


class QueuedTub(models.Model):
    ICE_3 = 'ICE_3'
    ICE_16 = 'ICE_16'
    ICE_BLOCK = 'ICE_BLOCK'
    BAGGED_ICE_16 = 'BAGGED_ICE_16'
    BAGGED_ICE_3 = 'BAGGED_ICE_3'
    FILL_CHOICES = (
        (ICE_3, '3 Mill'),
        (ICE_16, '16 Mill'),
        (ICE_BLOCK, 'Ice Block'),
        (BAGGED_ICE_3, '3 Mill Bagged'),
        (BAGGED_ICE_16, '16 Mill Bagged'),
    )
    fill = models.CharField(max_length=13, choices=FILL_CHOICES)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return "Dry Ice Tub: {}".format(self.fill)

class QueuedBottle(models.Model):
    ACETYLENE = 'AC'
    ARGON = 'AR'
    BEER_GAS = 'BG'
    CARBON_DIOXIDE = 'CD'
    GUINNESS_GAS = 'GS'
    HELIUM = 'HE'
    MIX_C2 = 'C2'
    MIX_C10 = 'C10'
    MIX_C25 = 'C25'
    NITROGEN = 'NI'
    OXYGEN = 'OX'
    STARGON = 'ST'
    SYPHON = 'SY'
    FILL_CHOICES = (
        (ACETYLENE, 'Acetylene'),
        (ARGON, 'Argon'),
        (BEER_GAS, 'Beer Gas'),
        (CARBON_DIOXIDE, 'Carbon Dioxide'),
        (GUINNESS_GAS, 'Guinness Gas'),
        (HELIUM, 'Helium'),
        (MIX_C2, 'Mix C2'),
        (MIX_C10, 'Mix C10'),
        (MIX_C25, 'Mix C25'),
        (NITROGEN, 'Nitrogen'),
        (OXYGEN, 'Oxygen'),
        (STARGON, 'Stargon'),
        (SYPHON, 'Syphon'),
    )
    SIZE_CHOICES = (
        ('T', 'T'),
        ('K', 'K'),
        ('S', 'S'),
        ('D', 'D'),
        ('Q', 'Q'),
        ('R', 'R'),
        ('50', '50'),
        ('40', '40'),
        ('20', '20'),
        ('15', '15'),
        ('10', '10'),
        ('5', '5'),
        ('2.5', '2.5'),
    )
    fill = models.CharField(max_length=13, choices=FILL_CHOICES)
    size = models.CharField(max_length=3, choices=SIZE_CHOICES)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return "Gas Bottle: {} {}".format(self.fill, self.size)

sales/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import *
from .forms import *
from datetime import date
from django.http import HttpResponse
from django.views.decorators.cache import cache_page

d = date.today()


def index(request):
    return render(request, 'sales/index.html')


# Add a new customer
class NewCustomer(CreateView):
    model = Customer
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(NewCustomer, self).get_context_data(**kwargs)
        context['manip_type'] = 'Add a New'
        return context


# Edit an existing customer
class EditCustomer(UpdateView):
    model = Customer
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(EditCustomer, self).get_context_data(**kwargs)
        context['manip_type'] = 'Update an Existing'
        return context


# List all the customers
class Customers(ListView):
    model = Customer


# Show details of a specific customer
class CustomerProfile(DetailView):
    model = Customer

    def get_context_data(self, **kwargs):
        context = super(CustomerProfile, self).get_context_data(**kwargs)
        context['customer'] = Customer.objects.get(customer_id=self.kwargs['pk'])
        customer = Customer.objects.get(customer_id=self.kwargs['pk'])
        phone_number = str(customer.phone_number)
        context['phone_number'] = "(" + phone_number[:3] + ") " + phone_number[3:6] + "-" + phone_number [6:]
        context['cust'] = self.kwargs['pk']
        return context


def pre_add_order(request):
    if request.method == 'POST':
        form = PreAddOrderForm(request.POST)
        if form.is_valid():
            cust_id = form.cleaned_data['customer_id']
            return redirect('sales:new_order', cust_id)
    else:
        form = PreAddOrderForm()
    return render(request, 'sales/pre_add_order.html', {'form': form})


# Add a new order
class NewOrder(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('sales:add_items')

    def get_success_url(self):
        return reverse('sales:add_items', args=(self.object.pk, self.kwargs['pk']))

    def get_context_data(self, **kwargs):
        context = super(NewOrder, self).get_context_data(**kwargs)
        context['manip_type'] = 'Add a New'
        return context

    def get_initial(self):
        initial = {}
        initial['customer'] = Customer.objects.get(customer_id=self.kwargs['pk'])
        initial['date_ordered'] = "{}-{}-{}".format(d.year, d.month, d.day)
        return initial


def add_items(request, pk, cust):
    context = {
        'pk': pk,
        'cust': cust,
        'tub_list': QueuedTub.objects.filter(order_id=pk),
        'bottle_list': QueuedBottle.objects.filter(order_id=pk),
    }
    return render(request, 'sales/add_items.html', context)


class NewQueuedTub(CreateView):
    model = QueuedTub
    form_class = NewQueuedTubForm

    def get_success_url(self):
        return reverse('sales:add_items', args=(self.kwargs['pk'],))

    def get_context_data(self, **kwargs):
        context = super(NewQueuedTub, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

    def get_initial(self):
        initial = {}
        initial['order'] = Order.objects.get(order_number=self.kwargs['pk'])
        return initial

    def form_valid(self, form):
        form.save()


def get_tubs(request, pk):
    tub_set = QueuedTub.objects.filter(order_id=pk)
    return render(request, 'sales/get_tubs.html', {'tub_set': tub_set})


def get_bottles(request, pk):
    bottle_set = QueuedBottle.objects.filter(order_id=pk)
    return render(request, 'sales/get_bottles.html', {'bottle_set': bottle_set})


class NewQueuedBottle(CreateView):
    model = QueuedBottle
    form_class = NewQueuedBottleForm

    def get_context_data(self, **kwargs):
        context = super(NewQueuedBottle, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        return context

    def get_initial(self):
        initial = {}
        initial['order'] = Order.objects.get(order_number=self.kwargs['pk'])
        return initial

    def form_valid(self, form):
        form.save()
        return render(self.request, 'sales/item_success.html')


# Show details of a specific order
class OrderDetail(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetail, self).get_context_data(**kwargs)
        context['customer'] = Customer.objects.get(customer_id=self.kwargs['cust'])
        customer = Customer.objects.get(customer_id=self.kwargs['cust'])
        phone_number = str(customer.phone_number)
        context['phone_number'] = "(" + phone_number[:3] + ") " + phone_number[3:6] + "-" + phone_number [6:]
        context['cust'] = self.kwargs['cust']
        context['date'] = d
        tubs = QueuedTub.objects.filter(order_id=self.kwargs['pk'])
        used_tubs = []
        context["tubs"] = {}
        for tub in tubs:
            if tub.fill not in used_tubs:
                context["tubs"]["{}".format(tub.fill)] = [1, "Unit", tub.fill, 400, 400]
                used_tubs.append("{}".format(tub.fill))
            else:
                context["tubs"]["{}".format(tub.fill)][0] += 1
                context["tubs"]["{}".format(tub.fill)][4] += 400
        bottles = QueuedBottle.objects.filter(order_id=self.kwargs['pk'])
        used_bottles = []
        context["bottles"] = {}
        for bottle in bottles:
            cur_bottle = bottle.fill + bottle.size
            if cur_bottle not in used_bottles:
                context["bottles"]["{}".format(cur_bottle)] = [1, "Unit", " - ".join([bottle.fill, bottle.size]), 20, 20]
                used_bottles.append("{}".format(cur_bottle))
            else:
                context["bottles"]["{}".format(cur_bottle)][0] += 1
                context["bottles"]["{}".format(cur_bottle)][4] += 20
        context['tub_total'] = QueuedTub.objects.filter(order_id=self.kwargs['pk']).count() * 400
        context['bottle_total'] = QueuedBottle.objects.filter(order_id=self.kwargs['pk']).count() * 20
        subtotal = context['tub_total'] + context['bottle_total']
        context['subtotal'] = subtotal
        tax = subtotal * .07
        context['tax'] = "{:.2f}".format(tax)
        total = subtotal + tax
        context['total'] = "{:.2f}".format(total)

        return context

templates/sales/add_items.html
{% extends 'sales/base.html' %}
{% block extra_js%}<script src="http://malsup.github.com/jquery.form.js"></script>{% endblock %}
{% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="card">
        <div class="card-header bg-secondary text-white text-center">Add Items</div>
        <div class="card-body">
          <div class="container">
            <div class="row">
              <div class="col" id="tubcol">
                <h4>Tubs</h4>
                <hr>
                <div id="tublist">
                  {% for tub in tub_list %}
                    <p>{{ tub }}</p>
                    <hr>
                  {% endfor %}
                </div>
                <a id="tubmodalopen" data-toggle='modal' data-target='#tubmodal' href="{% url 'sales:new_queued_tub' pk %}" class="btn btn-sm btn-success">Add Tub</a>
              </div>
              <div class="col">
                <h4>Bottles</h4>
                <hr>
                <div id="bottlelist">
                  {% for bottle in bottle_list %}
                    <p>{{ bottle }}</p>
                    <hr>
                  {% endfor %}
                </div>
                <a id="bottlemodalopen" data-toggle='modal' data-target='#bottlemodal' href="{% url 'sales:new_queued_bottle' pk %}" class="btn btn-sm btn-success">Add Bottle</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-2">
      <a href="{% url 'sales:customer_details' cust %}" class="mt-5 btn btn-primary">Submit Order</a>
    </div>
  </div>
</div>
<div class="modal" id="tubmodal"></div>
<div class="modal" id="bottlemodal"></div>
  <script>
    $(document).ready(function(){
      $("#tubmodalopen").click(function(){
        $("#tubmodal").load("{% url 'sales:new_queued_tub' pk %}");
      });
    $("#bottlemodalopen").click(function(){
        $("#bottlemodal").load("{% url 'sales:new_queued_bottle' pk %}");
      });
    });
  </script>
{% endblock %}

templates/sales/add_order_customer.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="card col-sm-5 mt-5 mx-auto bg-light">
        <div class="card-body text-center">
          <h3>Which Customer?</h3>
          <form action="{% url 'sales:pre_add_order' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
            {% endfor %}
            <div class="form-group">
              <button type="submit" class="btn btn-success mx-auto">Continue &rarr;</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/sales/customer_detail.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:customers' %}{% endblock %}

{% block body %}
  <div class="container-fluid">
    <div class="row mt-4">
      <div class="col-sm-3">
        <div class="card">
          <img class="card-img-top" src="" alt="No Company Image">
          <div class="card-body">
            <h4 class="card-title">{{ customer.company }}</h4>
            <p>{{ customer.contact_name }}<br>
            <span class="lead">{{ phone_number }}</span></p>
            <p>
              {{ customer.street_address }}<br>
              {{ customer.city }} {{ customer.state }} {{ customer.zipcode }}<br>
              {{ phone_number }}
            </p>
            <a href="{% url 'sales:edit_customer' cust %}" class="btn btn-outline-primary">Update Customer</a>
          </div>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="card">
          <div class="card-header">
            <h4>All Orders for <span style="color: dodgerblue">{{ customer.company }}</span></h4>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-2">
                <p><strong>Order id</strong></p>
              </div>
              <div class="col-4">
                <p><strong>Ship Date</strong></p>
              </div>
              <div class="col-2">
                <p><strong>Emp. Initials</strong></p>
              </div>
              <div class="col-2 text-right">
                <p><strong>View Order</strong></p>
              </div>
            </div>
            {% for order in customer.order_set.all %}
            <div class="row">
              <div class="col-2">
                <p>{{ order.order_number }}</p>
              </div>
              <div class="col-4">
                <p>{{ order.ship_date }}</p>
              </div>
              <div class="col-2">
                <p>{{ order.emp_init }}</p>
              </div>
              <div class="col-2 text-right">
                <a href="{% url 'sales:order_detail' customer.pk order.pk %}" class="btn btn-sm btn-primary">View Order</a>
              </div>
            </div>
            {% endfor %}
            <div class="row">
              <div class="col">
                <a href="{% url 'sales:new_order' customer.pk %}" class="btn btn-outline-success btn-sm">Add Order</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/sales/customer_list.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}
<div class="container-fluid">
{% for customer in object_list %}
  <a href="{% url 'sales:customer_details' customer.pk %}">
    <div class="row my-2">
      <div class="col">
        <div class="card p-2">
          <div class="row">
            <div class="col text-left">
              <p class="h4">{{ customer.company }}</p>
            </div>
          </div>
          <div class="row">
            <div class="col text-left">
              <p class="h6">Customer id: {{ customer.customer_id }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </a>
{% endfor %}
<div class="row my-5">
  <div class="col">
    <div>
      <a href="{% url 'sales:new_customer' %}" class="btn btn-outline-success btn-lg">New Customer</a>
    </div>
  </div>
</div>
</div>
{% endblock %}

templates/sales/get_bottles.html
{% for bottle in bottle_set %}
  <p>{{ bottle.fill }}</p>
{% endfor %}

templates/sales/get_tubs.html
{% for tub in tub_set %}
  <p>{{ tub.fill }}</p>
{% endfor %}

templates/sales/order_form_old.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="card col-sm-5 mt-5 mx-auto bg-light">
        <div class="card-body text-center">
          <h3>Adding Order</h3>
          <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
            {% endfor %}
            <div class="row mt-4">
              <div class="col text-center">
                <a class="btn btn-warning btn-sm text-white" href="{% url 'sales:collect_order_form_values' customer_id order_id %}">Add Bottle(s)</a>
              </div>
              <div class="col text-center">
                <a class="btn btn-primary btn-sm text-white" data-toggle="modal" data-target="#exampleModal">Add Tub(s)</a>
              </div>
            </div>
            <div class="form-group mt-5">
              <button class="btn btn-success mx-auto">Finish</button>
            </div>
          </form>
        <ul>
        {% for item in items %}
          <li>{{ item }}</li>
        {% endfor %}
        </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" method="post">
            {% csrf_token %}
            {% for field in form2 %}
                <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
            {% endfor %}
            <div class="form-group">
              <button type="submit" class="btn btn-success mx-auto">&larr; Add Item</button>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/sales/order_update.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}

{% endblock %}

templates/sales/pre_add_order.html
<!-- File for creating and updating tubs in warehouse -->
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}
  <div class="container-fluid">
    <div class="row">
      <div class="card col-sm-5 mt-5 mx-auto bg-light">
        <div class="card-body text-center">
          <h3>Adding Order</h3>
          <form action="{% url 'sales:pre_add_order' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
            {% endfor %}
            <div class="form-group">
              <button class="btn btn-success mx-auto">Add Order</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/sales/pre_order_update.html
{% extends 'sales/base.html' %}
{% block back_link %}{% url 'sales:index' %}{% endblock %}
{% block body %}

{% endblock %}