Final/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^sales/', include('sales.urls', namespace='sales')),
    url(r'^warehouse/', include('warehouse.urls', namespace='warehouse')),

    # ==================== TESTING PURPOSES ==================== #
    url(r'^testing/$', views.testing, name='testing'),
    url(r'^add_tubs/$', views.add_tubs, name='add_tubs'),
    url(r'^del_tubs/$', views.del_tubs, name='del_tubs'),
    url(r'^add_bottles/$', views.add_bottles, name='add_bottles'),
    url(r'^del_bottles/$', views.del_bottles, name='del_bottles'),
    url(r'^add_customers/$', views.add_customers, name='add_customers'),
    url(r'^del_customers/$', views.del_customers, name='del_customers'),
    url(r'^add_orders/$', views.add_orders, name='add_orders'),
    url(r'^del_orders/$', views.del_orders, name='del_orders'),
]

warehouse/urls.py
from django.conf.urls import url, include
from . import views

app_name="warehouse"

urlpatterns = [

    # ==================== INDEX ==================== #
    url(r'^$', views.index, name="index"),

    # ==================== BOTTLES ==================== #
    url(r'^bottles/$', views.bottles, name='bottles'),
    url(r'^bottles/add/$', views.BottlesAdd.as_view(), name='bottles_add'),
    url(r'^bottles/pre_update/$', views.pre_bottles_update, name='pre_bottles_update'),
    url(r'^bottles/update/(?P<pk>\w+)$', views.BottlesUpdate.as_view(), name='bottles_update'),
    url(r'^bottles/pre_remove/$', views.pre_bottles_remove, name='pre_bottles_remove'),
    url(r'^bottles/remove/(?P<pk>\w+)$', views.BottlesRemove.as_view(), name='bottles_remove'),

    # ==================== TUBS ==================== #
    url(r'^tubs/$', views.tubs, name='tubs'),
    url(r'^tubs/add/$', views.TubsAdd.as_view(), name='tubs_add'),
    url(r'^tubs/pre_update/$', views.pre_tubs_update, name='pre_tubs_update'),
    url(r'^tubs/update/(?P<pk>\w+)$', views.TubsUpdate.as_view(), name='tubs_update'),
    url(r'^tubs/pre_remove/$', views.pre_tubs_remove, name='pre_tubs_remove'),
    url(r'^tubs/remove/(?P<pk>\w+)$', views.TubsRemove.as_view(), name='tubs_remove'),

    # ==================== ORDERS ==================== #
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^orders/pre-ship/$', views.pre_ship, name='pre_ship_order'),
    url(r'^orders/pre-return', views.pre_return, name='pre_return_order'),
    url(r'^orders/(?P<order_num>[0-9]+)/ship/$', views.ship_order, name='order_ship'),
    url(r'^orders/(?P<order_num>[0-9]+)/return/$', views.return_order, name='order_return'),
    url(r'^orders/(?P<order_num>[0-9]+)/ship/add_tub', views.add_order_tub, name='add_order_tub'),
    url(r'^orders/(?P<order_num>[0-9]+)/ship/add_bottle', views.add_order_bottle, name='add_order_bottle'),
    url(r'^orders/(?P<order_num>[0-9]+)/ship/return_tub', views.return_order_tub, name='return_order_tub'),
    url(r'^orders/(?P<order_num>[0-9]+)/ship/return_bottle', views.return_order_bottle, name='return_order_bottle'),
]

warehouse/models.py
from django.db import models

warehouse/forms.py
from django import forms
from inventory.models import *


# ==================== TUBS FORMS ==================== #

# Form class for adding tubs, overriding the default one
class TubsAddForm(forms.ModelForm):
    # Override the default __init__ to add .widget.attrs css to each field
    def __init__(self, *args, **kwargs):
        super(TubsAddForm, self).__init__(*args, **kwargs)
        self.fields['emp_init'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['fill'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['status'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['serial_number'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['barcode'].widget.attrs = {
            'class': 'form-control'
        }

    # Meta data here tells the class what model to use, and what fields to use
    class Meta:
        model = Tub
        fields = ['emp_init', 'fill', 'status', 'serial_number', 'barcode']


# Form for getting tub barcode pre-updating it
class PreTubsUpdateForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class TubsUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TubsUpdateForm, self).__init__(*args, **kwargs)
        self.fields['order'].required = False
        self.fields['emp_init'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['fill'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['status'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['serial_number'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['barcode'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['order'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = Tub
        fields = '__all__'


# Form for getting tub barcode pre-removing it
class PreTubsRemoveForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


# ==================== BOTTLES FORMS ==================== #

# Form class for adding tubs, overriding the default one
class BottlesAddForm(forms.ModelForm):
    # Override the default __init__ to add .widget.attrs css to each field
    def __init__(self, *args, **kwargs):
        super(BottlesAddForm, self).__init__(*args, **kwargs)
        self.fields['emp_init'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['fill'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['size'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['status'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['serial_number'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['barcode'].widget.attrs = {
            'class': 'form-control'
        }

    # Meta data here tells the class what model to use, and what fields to use
    class Meta:
        model = Bottle
        fields = ['emp_init', 'fill', 'serial_number', 'size', 'status', 'barcode']


# Form for getting tub barcode pre-updating it
class PreBottlesUpdateForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class BottlesUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BottlesUpdateForm, self).__init__(*args, **kwargs)
        self.fields['order'].required = False
        self.fields['emp_init'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['fill'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['size'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['status'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['serial_number'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['barcode'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['order'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = Bottle
        fields = '__all__'


# Form for getting tub barcode pre-removing it
class PreBottlesRemoveForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))

# ==================== ORDERS FORMS ==================== #


class AddOrderTubForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class AddOrderBottleForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class PreShipForm(forms.Form):
    order_number = forms.CharField(label='Order Number', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class PreReturnForm(forms.Form):
    barcode = forms.CharField(label='Item Barcode', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class ReturnOrderTubForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))


class ReturnOrderBottleForm(forms.Form):
    barcode = forms.CharField(label='Barcode', max_length=20, widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))

warehouse/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import *
from sales.models import *
from inventory.models import *
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse


# ==================== INDEX ==================== #
def index(request):
    return render(request, 'warehouse/index.html')


# ==================== TUBS ==================== #
def tubs(request):
    return render(request, 'warehouse/tubs.html')


class TubsAdd(CreateView):
    model = Tub
    form_class = TubsAddForm


def pre_tubs_update(request):
    if request.method == 'POST':
        form = PreTubsUpdateForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            serial_number = Tub.objects.get(barcode=barcode).serial_number
            # calls a url with a namespace, which calls a view, both get the serial number
            return redirect('warehouse:tubs_update', serial_number)
    else:
        form = PreTubsUpdateForm()
    return render(request, 'warehouse/pre_tub_update.html', {'form': form})


class TubsUpdate(UpdateView):
    model = Tub
    form_class = TubsUpdateForm
    template_name_suffix = '_update_form'


def pre_tubs_remove(request):
    if request.method == 'POST':
        form = PreTubsRemoveForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            serial_number = Tub.objects.get(barcode=barcode).serial_number
            return redirect('warehouse:tubs_remove', serial_number)
    else:
        form = PreTubsRemoveForm()
    return render(request, 'warehouse/pre_tub_remove.html', {'form': form})


class TubsRemove(DeleteView):
    model = Tub
    success_url = reverse_lazy('warehouse:tubs')


# ==================== BOTTLES ==================== #
def bottles(request):
    return render(request, 'warehouse/bottles.html')


class BottlesAdd(CreateView):
    model = Bottle
    form_class = BottlesAddForm


def pre_bottles_update(request):
    if request.method == 'POST':
        form = PreBottlesUpdateForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            serial_number = Bottle.objects.get(barcode=barcode).serial_number
            # calls a url with a namespace, which calls a view, both get the serial number
            return redirect('warehouse:bottles_update', serial_number)
    else:
        form = PreBottlesUpdateForm()
    return render(request, 'warehouse/pre_bottle_update.html', {'form': form})


class BottlesUpdate(UpdateView):
    model = Bottle
    form_class = BottlesUpdateForm
    template_name_suffix = '_update_form'


def pre_bottles_remove(request):
    if request.method == 'POST':
        form = PreBottlesRemoveForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode'].upper()
            serial_number = Bottle.objects.get(barcode=barcode).serial_number
            return redirect('warehouse:bottles_remove', serial_number)
    else:
        form = PreBottlesRemoveForm()
    return render(request, 'warehouse/pre_bottle_remove.html', {'form': form})


class BottlesRemove(DeleteView):
    model = Bottle
    success_url = reverse_lazy('warehouse:bottles')


# ==================== ORDERS ==================== #
def orders(request):
    return render(request, 'warehouse/orders.html')


def pre_ship(request):
    if request.method == 'POST':
        form = PreShipForm(request.POST)
        if form.is_valid():
            order_number = form.cleaned_data['order_number']
            return redirect('warehouse:order_ship', order_number)
    else:
        form = PreShipForm()
    return render(request, 'warehouse/pre-ship.html', {'form': form})


def ship_order(request, order_num):
    if request.method == 'POST':
        a = Order.objects.get(order_number=order_num)
        a.status = 'SHIPPED'
        a.save()
        return render(request, 'warehouse/orders.html')
    else:
        order = Order.objects.get(order_number=order_num)
        queued_bottles = QueuedBottle.objects.filter(order_id=order_num)
        queued_tubs = QueuedTub.objects.filter(order_id=order_num)
        added_bottles = Bottle.objects.filter(order=order, )
        added_tubs = Tub.objects.filter(order=order)
        context = {
            'order': order,
            'queued_bottles': queued_bottles,
            'queued_tubs': queued_tubs,
            'order_num': order_num,
            'added_bottles': added_bottles,
            'added_tubs': added_tubs,
        }
        return render(request, 'warehouse/ship-order.html', context)


def add_order_tub(request, order_num):
    if request.method == 'POST':
        form = AddOrderTubForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            tub = Tub.objects.get(barcode=barcode)
            order = Order.objects.get(order_number=order_num)
            tub.order = order
            tub.status = 'CS'
            tub.save()
            return redirect('warehouse:order_ship', order_num)
    else:
        form = AddOrderTubForm()
    return render(request, 'warehouse/add_order_tub.html', {'form': form, 'order_num': order_num})


def add_order_bottle(request, order_num):
    if request.method == 'POST':
        form = AddOrderBottleForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            bottle = Bottle.objects.get(barcode=barcode)
            order = Order.objects.get(order_number=order_num)
            bottle.order = order
            bottle.status = 'CS'
            bottle.save()
            return redirect('warehouse:order_ship', order_num)
    else:
        form = AddOrderBottleForm()
    return render(request, 'warehouse/add_order_bottle.html', {'form': form, 'order_num': order_num})


def pre_return(request):
    if request.method == 'POST':
        form = PreReturnForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            try:
                item = Bottle.objects.get(barcode=barcode)
            except ObjectDoesNotExist:
                item = Tub.objects.get(barcode=barcode)
            order_number = item.order.order_number
            return redirect('warehouse:order_return', order_number)
    else:
        form = PreReturnForm()
    return render(request, 'warehouse/pre-return.html', {'form': form})


def return_order(request, order_num):
    order = Order.objects.get(order_number=order_num)
    added_bottles = Bottle.objects.filter(order_id=order_num, status='CS')
    added_tubs = Tub.objects.filter(order_id=order_num, status='CS')
    returned_bottles = Bottle.objects.filter(order=order, status='DE')
    returned_tubs = Tub.objects.filter(order=order, status='DE')
    order_number = order.order_number
    context = {
        'order': order,
        'added_bottles': added_bottles,
        'added_tubs': added_tubs,
        'order_num': order_number,
        'returned_tubs': returned_tubs,
        'returned_bottles': returned_bottles
    }
    return render(request, 'warehouse/return-order.html', context)


def return_order_tub(request, order_num):
    if request.method == 'POST':
        form = ReturnOrderTubForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            tub = Tub.objects.get(barcode=barcode)
            tub.status = 'DE'
            tub.save()
            return redirect('warehouse:order_return', order_num)
    else:
        form = ReturnOrderTubForm()
    return render(request, 'warehouse/return_order_tub.html', {'form': form, 'order_num': order_num})


def return_order_bottle(request, order_num):
    if request.method == 'POST':
        form = ReturnOrderBottleForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['barcode']
            bottle = Bottle.objects.get(barcode=barcode)
            order = Order.objects.get(order_number=order_num)
            bottle.order = order
            bottle.status = 'DE'
            bottle.save()
            return redirect('warehouse:order_return', order_num)
    else:
        form = ReturnOrderBottleForm()
    return render(request, 'warehouse/return_order_bottle.html', {'form': form, 'order_num': order_num})

templates/warehouse/add_order_bottle.html
<div class="modal-dialog">
  <form action="{% url 'warehouse:add_order_bottle' order_num %}" method="post" id="add_order_bottle" class="form">
  {% csrf_token %}
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-center">Add Bottle to Order</h4>
        <button type="button" class="close text-right" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
        </button>
      </div>
      <div class="modal-body">
        {% for field in form %}
          <div class="form-group">
            <div class="form-row">
              <label class="col-4 text-right">{{ field.label_tag }}</label>
              <div class="col-6 text-left">{{ field }}</div>
            </div>
          </div>
        {% endfor %}
      </div>
    <div class="modal-footer">
      <div class="form-group">
        <button type="submit" class="btn btn-success" id="submit">Submit</button>
      </div>
    </div>
    </div>
  </form>
</div>
<script>
  var form_options = { target: '#addbottlemodal', success: function(response) {} };
  $('#add_order_bottle').ajaxForm(form_options);
  $('#submit').click(function () {
      $('#addbottlemodal').modal('hide');
      setTimeout(function() { location.reload(false) }, 100);
  })
</script>

templates/warehouse/bottles.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:index' %}{% endblock %}

{% block body %}

<div class="container-fluid mt-5 text-center">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card bg-light">
        <div class="card-body">
          <p><a href="{% url 'warehouse:bottles_add' %}" class="btn btn-outline-primary my-4">ADD BOTTLE</a></p>
          <p><a href="{% url 'warehouse:pre_bottles_update' %}" class="btn btn-outline-primary my-4">UPDATE BOTTLE</a></p>
          <p><a href="{% url 'warehouse:pre_bottles_remove' %}" class="btn btn-outline-primary my-4">REMOVE BOTTLE</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/warehouse/index.html
{% extends 'warehouse/base.html' %}

{% block body %}

<div class="container-fluid mt-5 text-center">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card bg-light">
        <div class="card-body">
          <p><a href="{% url 'warehouse:tubs' %}" class="btn btn-outline-warning my-4">TUBS</a></p>
          <p><a href="{% url 'warehouse:bottles' %}" class="btn btn-outline-primary my-4">BOTTLES</a></p>
          <p><a href="{% url 'warehouse:orders' %}" class="btn btn-outline-danger my-4">ORDERS</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/warehouse/orders.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:index' %}{% endblock %}

{% block body %}

<div class="container-fluid mt-5 text-center">
  <div class="row">
    <div class="col-md-4 mx-md-auto">
      <div class="card bg-light">
        <div class="card-body">
          <p><a href="{% url 'warehouse:pre_ship_order' %}" class="btn btn-outline-danger my-4">SHIP ORDER</a></p>
          <p><a href="{% url 'warehouse:pre_return_order' %}" class="btn btn-outline-danger my-4">RETURN ORDER</a></p>
{#          <p> no function <br><a href="" class="btn btn-outline-danger my-4">CHANGE ORDER</a></p>#}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/warehouse/pre-return.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:orders' %}{% endblock %}

{% block body %}
<div class="container">
  <div class="row mt-5 justify-content-center">
    <div class="col-7">
      <div class="card">
        <div class="card-header"><h4>Enter Item Barcode:</h4></div>
        <div class="card-body">
        <form action="{% url 'warehouse:pre_return_order' %}" method="post">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
          {% endfor %}
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/warehouse/pre-ship.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:orders' %}{% endblock %}

{% block body %}
<div class="container">
  <div class="row mt-5 justify-content-center">
    <div class="col-7">
      <div class="card">
        <div class="card-header"><h4>Enter Order Number:</h4></div>
        <div class="card-body">
        <form action="{% url 'warehouse:pre_ship_order' %}" method="post">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group">
                  <div class="form-row">
                    <label class="col-sm-3 offset-sm-1 text-right">{{ field.label_tag }}</label>
                    <div class="col-sm-5">{{ field }}</div>
                  </div>
                </div>
          {% endfor %}
        </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/warehouse/return-order.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:orders' %}{% endblock %}
{% block body %}
<div class="container">
  <div class="row mt-3">
    <div class="col-6">
      <h2 class="text-center">Added Items</h2>
      <hr>
      <h6>Bottles:</h6>
      {% for bottle in added_bottles %}
        <p>{{ bottle.fill }}-{{ bottle.size }} {{ bottle.barcode }}</p>
      {% endfor %}
      <h6>Tubs:</h6>
      {% for tub in added_tubs %}
          <p>{{ tub.fill }} {{ tub.barcode }}</p>
      {% endfor %}
    </div>
    <div class="col-6">
      <h2 class="text-center">Returned Items</h2>
      <hr>
      <h6>Bottles:</h6>
      {% for bottle in returned_bottles %}
        <p>{{ bottle.fill }}-{{ bottle.size }} {{ bottle.barcode }}</p>
      {% endfor %}
      <h6>Tubs:</h6>
      {% for tub in returned_tubs %}
        <p>{{ tub.fill }} {{ tub.barcode }}</p>
      {% endfor %}
      <a id="tubmodalopen" data-toggle='modal' data-target='#returntubmodal' href="{% url 'warehouse:return_order_tub' order_num %}" class="btn btn-sm btn-warning">Return Tub from Order</a>
      <a id="bottlemodalopen" data-toggle='modal' data-target='#returnbottlemodal' href="{% url 'warehouse:return_order_bottle' order_num %}" class="btn btn-sm btn-info">Return Bottle from Order</a>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col text-center">
      <a href="{% url 'warehouse:orders' %}" class="btn btn-primary">Submit Return</a>
    </div>
  </div>
</div>
<div class="modal" id="returntubmodal"></div>
<div class="modal" id="returnbottlemodal"></div>
<script>
  $(document).ready(function(){
      $('#tubmodalopen').click(function () {
          $('#returntubmodal').load("{% url 'warehouse:return_order_tub' order_num %}");
      });
      $('#bottlemodalopen').click(function () {
          $('#returnbottlemodal').load("{% url 'warehouse:return_order_bottle' order_num %}");
      });
  });
</script>
{% endblock %}

templates/warehouse/ship-order.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:orders' %}{% endblock %}
{% block extra_js%}<script src="http://malsup.github.com/jquery.form.js"></script>{% endblock %}
{% block body %}
<div class="container">
  <div class="row mt-3">
    <div class="col-6">
      <h2 class="text-center">Queued Items</h2>
      <hr>
      <h6>Bottles:</h6>
      {% for bottle in queued_bottles %}
        <p>{{ bottle.fill }}-{{ bottle.size }}</p>
      {% endfor %}
      <h6>Tubs:</h6>
      {% for tub in queued_tubs %}
          <p>{{ tub.fill }}</p>
      {% endfor %}
    </div>
    <div class="col-6">
      <h2 class="text-center">Added Items</h2>
      <hr>
      <h6>Bottles:</h6>
      {% for bottle in added_bottles %}
        <p>{{ bottle.fill }}-{{ bottle.size }} {{ bottle.barcode }}</p>
      {% endfor %}
      <h6>Tubs:</h6>
      {% for tub in added_tubs %}
        <p>{{ tub.fill }} {{ tub.barcode }}</p>
      {% endfor %}
      <a id="tubmodalopen" data-toggle='modal' data-target='#addtubmodal' href="{% url 'warehouse:add_order_tub' order_num%}" class="btn btn-sm btn-warning">Add Tub to Order</a>
      <a id="bottlemodalopen" data-toggle='modal' data-target='#addbottlemodal' href="{% url 'warehouse:add_order_bottle' order_num%}" class="btn btn-sm btn-info">Add Bottle to Order</a>
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col text-center">
      <form action="{% url 'warehouse:order_ship' order.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <button type='submit' class="btn btn-primary">Submit Order</button>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="modal" id="addtubmodal"></div>
<div class="modal" id="addbottlemodal"></div>
<script>
  $(document).ready(function(){
      $('#tubmodalopen').click(function () {
          $('#addtubmodal').load("{% url 'warehouse:add_order_tub' order_num %}");
      });
      $('#bottlemodalopen').click(function () {
          $('#addbottlemodal').load("{% url 'warehouse:add_order_bottle' order_num %}");
      });
  });
</script>
{% endblock %}

templates/warehouse/tubs.html
{% extends 'warehouse/base.html' %}
{% block back_link %}{% url 'warehouse:index' %}{% endblock %}

{% block body %}

<div class="container-fluid mt-5 text-center">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card bg-light">
        <div class="card-body">
          <p><a href="{% url 'warehouse:tubs_add' %}" class="btn btn-outline-warning my-4">ADD TUB</a></p>
          <p><a href="{% url 'warehouse:pre_tubs_update' %}" class="btn btn-outline-warning my-4">UPDATE TUB</a></p>
          <p><a href="{% url 'warehouse:pre_tubs_remove' %}" class="btn btn-outline-warning my-4">REMOVE TUB</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}